notes_app/urls.py
from django.urls import path, include
from . import views


from .views import (NoteListView, NoteDetailView,
                    NoteCreateView, NoteUpdateView,
                    NoteDeleteView)


urlpatterns = [
    path('', NoteListView.as_view(), name='home'),
    path('note/<slug:slug>/', NoteDetailView.as_view(), name='note_detail'),
    path('creat-note/', NoteCreateView.as_view(), name='creat_note'),
    path('edit-note/<slug:slug>/', NoteUpdateView.as_view(), name='edit_note'),
    path('delete-note/<slug:slug>/', NoteDeleteView.as_view(),
         name='delete_note'),

    path('folder/<slug:category_slug>/', views.category_list,
         name='category_list'),

    path('starred-categories/', views.starred_categories,
         name='starred_categories'),
]

notesapp_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes_app.urls')),
    path('kanban/', include('kanban_app.urls')),
    path('todo/', include('todo_app.urls')),
    # path('profile/', include('profile_app.urls')),
    # path("__reload__/", include("django_browser_reload.urls")),
]

# handler403 = "board_app.views.access_denied"
# handler400 = "board_app.views.bad_request"
# handler404 = "board_app.views.page_not_found_view"
# handler500 = "board_app.views.handler500"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todo_app/urls.py
from django.urls import path
from .views import create_item, delete_item

from .views import (
    ToDoListView, ToDoDetailView, ItemsListView
)

urlpatterns = [
    path('', ToDoListView.as_view(), name='todo'),
    path('todo_items/<slug:todo_slug>/',
         ItemsListView.as_view(), name='todo_items'),
    path('todo/<slug:slug>/', ToDoDetailView.as_view(), name='todo_detail'),

    # path('delete/<int:pk>', ItemDeleteView
    #      .as_view(), name='delete_item'),
]


htmxpatterns = [
    # path('create_item/', views.create_item, name='create_item'),

    path('todo/<slug:todo_slug>/create_item/', create_item, name='create_item'),
    path('todo/<slug:todo_slug>/', ToDoDetailView.as_view(), name='todo_detail'),
    path('delete_item/<int:item_pk>/', delete_item, name='delete_item'),
    # path('mark_item/<int:pk>/', views.mark_item, name='mark_item'),
]


urlpatterns += htmxpatterns

notes_app/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

from django.contrib.auth.models import User

from django.utils.text import slugify
from django_quill.fields import QuillField


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, unique=True)
    order = models.PositiveIntegerField(default=0)  # Add the order field
    parent_category = models.ForeignKey(
        'self', on_delete=models.CASCADE, null=True, blank=True, related_name='subcategories')
    is_starred = models.BooleanField(default=False)  # field for starred category
    is_deletable = models.BooleanField(default=True)
    class Meta:
        verbose_name_plural = "categories"

    class Meta:
        ordering = ('order',)

    def __str__(self):
        return self.name

    # @classmethod
    # def create(cls, name, is_starred=False, is_deletable=True):
    #     return cls.objects.create(name=name, is_starred=is_starred)

    def delete_category(self):
        if self.is_deletable:
            self.delete()
        else:
            raise Exception("Cannot delete this category")
    def get_absolute_url(self):
        return reverse('board_app:category_list', args=[self.slug])

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         base_slug = slugify(self.name)
    #         slug = base_slug
    #         counter = 1
    #         while Category.objects.filter(slug=slug).exists():
    #             slug = f"{base_slug}-{counter}"
    #             counter += 1
    #         self.slug = slug
    #     super().save(*args, **kwargs)


    @classmethod
    def create(cls, name, is_deletable=True, is_starred=False):
        category = cls(name=name, is_deletable=is_deletable, is_starred=is_starred)
        category.save()  # Call save to generate slug
        return category

if not Category.objects.exists():
    Category.objects.create(name="Projects", is_deletable=True, is_starred=True, order=0)
    Category.objects.create(name="Areas", is_deletable=True, is_starred=True, order=1)
    Category.objects.create(name="Resources", is_deletable=True, is_starred=True, order=2)
    Category.objects.create(name="Archives", is_deletable=True, is_starred=True, order=3)


class Note(models.Model):

    title = models.CharField(max_length=100)
    image = models.ImageField(null=True, blank=True, upload_to='note_image')
    content = QuillField(null=True)
    slug = models.SlugField(max_length=250, unique=True)
    date_created = models.DateTimeField(default=timezone.now, editable=False)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="note_author")

    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ('-date_created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('note_detail', kwargs={'slug': self.slug})

    def category_name(self):
        all = []
        for a in self.category.all():
            all.append(str(a))
        return "; ".join(all)

    def save(self, *args, **kwargs):
        if not self.slug:
            # Create a unique slug based on the title and a timestamp to prevent identical slug
            base_slug = slugify(self.title)
            unique_slug = base_slug
            counter = 1

            while Note.objects.filter(slug=unique_slug).exists():
                unique_slug = f"{base_slug}-{counter}"
                counter += 1

            self.slug = unique_slug

        super(Note, self).save(*args, **kwargs)

notes_app/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Fieldset
from django.contrib.auth.models import User
# from django_quill.forms import QuillFormField
from .models import Note


class NoteForm(forms.ModelForm):
    # content = QuillFormField()

    class Meta:
        model = Note
        fields = ['title', 'image',
                  'content', 'category']

    def __init__(self, *args, **kwargs):
        super(NoteForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        # self.fields['title'].help_text = "Please select bla bla bla"

        self.fields['title'].widget.attrs['placeholder'] = 'Add a title to your note*'
        self.fields['content'].widget.attrs['placeholder'] = 'Enter your content here'
        self.fields['category'].help_text = "Please select your folder"

notes_app/views.py
from .forms import NoteForm
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import generic
from django.contrib import messages
import json
from django.contrib.auth.models import User

from django.urls import reverse
from django.shortcuts import get_object_or_404, render, redirect

from .models import Note, Category

from django.views.generic import (
    ListView, DetailView,
    CreateView, DeleteView,
    UpdateView
)
from .forms import NoteForm


# --------------------------------
#   note views
# --------------------------------
class NoteListView(ListView):
    """ The homepage """

    model = Note
    context_object_name = 'notes'
    # paginate_by = 6
    template_name = "notes_app/index.html"


class NoteDetailView(DetailView):
    model = Note

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context


class NoteCreateView(LoginRequiredMixin, CreateView):
    model = Note
    form_class = NoteForm
    template_name = "notes_app/creat_note.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        content_data = json.loads(form.cleaned_data['content'])
        content = content_data.get('html', '')

        # Retrieve the category slug from the URL parameter
        category_slug = self.request.GET.get('category')

        if category_slug:
            # Get the category object based on the slug
            category = get_object_or_404(Category, slug=category_slug)
            form.instance.category = category

        response = super().form_valid(form)

        return response


class NoteUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Note

    form_class = NoteForm
    template_name = 'notes_app/edit_note.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, 'Note updated successfully')
        return super().form_valid(form)

    def test_func(self):
        note = self.get_object()
        return self.request.user == note.author


# def duplicate_note(request, note_slug):
#     try:
#         original_note = Note.objects.get(slug=note_slug)
#     except Note.DoesNotExist:
#         # Handle the case where the original note doesn't exist
#         return redirect('error_page')

#     if request.method == 'POST':
#         duplicate_form = DuplicateNoteForm(original_note, request.POST)
#         if duplicate_form.is_valid():
#             new_note = duplicate_form.save(commit=False)
#             new_note.author = request.user
#             new_note.save()
#             return redirect('note_detail', slug=new_note.slug)
#     else:
#         duplicate_form = DuplicateNoteForm(original_note)

#     return render(request, 'notes_app/duplicate_note_confirm.html', {'original_note': original_note, 'duplicate_form': duplicate_form})


class NoteDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Note
    template_name = 'notes_app/delete_note.html'
    success_url = '/'

    def test_func(self):
        note = self.get_object()
        # if self.request.user == post.author:
        if self.request.user == note.author or self.request.user.is_superuser:

            return True
        return False

# TODO: messages not showing up, fix, CSS also added to tey debug
    def form_valid(self, form):
        messages.success(self.request, 'Note deleted.')
        return super().form_valid(form)


# --------------------------------
#   category/folder views
# --------------------------------


def categories(request):
    all_categories = Category.objects.all()
    return {
        'all_categories': all_categories
    }


def starred_categories(request):

# Create initial categories
    # if not Category.objects.exists():
    #     Category.create(name="Projects", is_deletable=True, is_starred=True)
    #     Category.create(name="Areas", is_deletable=True,is_starred=True)
    #     Category.create(name="Resources", is_deletable=True, is_starred=True)
    #     Category.create(name="Archives", is_deletable=True, is_starred=True)

    starred_categories = Category.objects.filter(is_starred=True)
    # print('starred_categories', starred_categories)
    
    # for category in starred_categories:
    #     category.detail_url = reverse('category_detail', kwargs={'slug': category.slug})
    #     print(f"Category: {category.name}, Detail URL: {category.detail_url}")

    context = {
        'starred_categories': starred_categories
    }

    return render(request, 'notes_app/starred_categories.html', context)



def category_list(request, category_slug):

    category = get_object_or_404(Category, slug=category_slug)
    notes = Note.objects.filter(category=category)

    # Get subcategories of the current category
    subcategories = category.subcategories.all()
    # starred_categories = Category.objects.filter(is_starred=True)
    page_title = category.name

    context = {
        'notes': notes,
        'category': category,
        'subcategories': subcategories,
        # 'starred_categories': starred_categories,
        'page_title': page_title,
    }

    return render(request, 'notes_app/category_list.html', context)

notes_app/templates/notes_app/components/para_infobox.html
<div class="mb-6">
    <div id="toast-interactive"
        class="w-full p-4 text-gray-500 bg-white rounded-lg shadow dark:bg-gray-800 dark:text-gray-400" role="alert">
        <div class="flex">
            <div
                class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-blue-500 bg-blue-100 rounded-lg dark:text-blue-300 dark:bg-blue-900">
                <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                    viewBox="0 0 18 20">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M15.147 15.085a7.159 7.159 0 0 1-6.189 3.307A6.713 6.713 0 0 1 3.1 15.444c-2.679-4.513.287-8.737.888-9.548A4.373 4.373 0 0 0 5 1.608c1.287.953 6.445 3.218 5.537 10.5 1.5-1.122 2.706-3.01 2.853-6.14 1.433 1.049 3.993 5.395 1.757 9.117Z" />
                </svg>
                <span class="sr-only">Fire icon</span>
            </div>
            <div class="ml-3 text-sm font-normal">
                <span class="mb-1 text-sm font-semibold text-gray-900 dark:text-white">PARA Method:</span>
                <div class="mb-2 text-sm font-normal">Get More Done
                    With This Productivity Framework for Organizing Your Life</div>
                <div class="pb-6">
                    <div class="py-2">
                        <h3 class="text-xl text-gray-800">Projects</h3>
                        <p>Projects usualy short-term, aggregate commitments that require more than one action step to
                            complete. That can
                            be anything from a new business venture to that book you’ve always wanted to write.</p>
                    </div>
                    <div class="py-2">
                        <h3 class="text-xl text-gray-800">Areas</h3>
                        <p>Long-term commitments with the singular goal of improving specific areas of your daily life.
                            Unlike Projects, Areas usually don’t have a set deadline.</p>
                    </div>
                    <div class="py-2">
                        <h3 class="text-xl text-gray-800">Resources</h3>
                        <p>Resources are a smorgasbord of books, articles, tips & tricks, personal notes and a range of
                            topics you’re interested in and learning about</p>
                    </div>
                    <div class="py-2">
                        <h3 class="text-xl text-gray-800">Archives</h3>
                        <p>Archives act as storage for any information you don’t necessarily need today but may want to
                            reference it in the future. That also includes completed and paused projects.</p>
                    </div>
                </div>

                <a href="#"
                    class="inline-flex w-full md:w-auto justify-center  py-1.5 px-4 text-xs font-medium text-center text-gray-900 bg-white border border-gray-300 rounded hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:bg-gray-600 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-700 dark:focus:ring-gray-700">
                    Find out more
                </a>

            </div>
            <button type="button"
                class="ml-auto -mx-1.5 -my-1.5 bg-white items-center justify-center flex-shrink-0 text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700"
                data-dismiss-target="#toast-interactive" aria-label="Close">
                <span class="sr-only">Close</span>
                <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                    viewBox="0 0 14 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                </svg>
            </button>
        </div>
    </div>
</div>

notes_app/templates/notes_app/components/starred_categories_partial.html
<!-- <h2>Starred Categories</h2>
<ul>
    {% for starred_category in starred_categories %}
    <li>{{ starred_category.name }}</li>
    {% endfor %}
</ul> -->


<!-- folders -->

<li>
    <div class="text-slate-500 ml-2 mt-8 text-base">Starred Folders</div>
</li>


{% for starred_category in starred_categories %}
<li>
    <a href="/folder/{{starred_category.slug}}"
        class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
        <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400
                group-hover:text-gray-600 dark:group-hover:text-white" aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
            <path
                d="M22 8V20C22 20.5523 21.5523 21 21 21H3C2.44772 21 2 20.5523 2 20V7H21C21.5523 7 22 7.44772 22 8ZM12.4142 5H2V4C2 3.44772 2.44772 3 3 3H10.4142L12.4142 5Z"
                fill="currentColor"></path>
        </svg>
        <span class="flex-1 ml-3 whitespace-nowrap">
            {{ starred_category.name|title }}
        </span>
        <span
            class="inline-flex items-center justify-center w-3 h-3 p-3 ml-3 text-sm font-medium text-violet-800 bg-violet-100 rounded-full dark:bg-blue-900 dark:text-blue-300">
            {{ starred_category.note_set.count }}

        </span>
    </a>
</li>
{% endfor %}



<li class="pt-2 pb-6">
    <button class="flex items-center border rounded-md p-2 w-full text-gray-900 hover:bg-gray-100">
        <svg class="mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="18" height="18">
            <path d="M11 11V5H13V11H19V13H13V19H11V13H5V11H11Z"></path>
        </svg>
        <span>Add folder</span>
    </button>
</li>